// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://127.0.0.1:44355/' | (string & {});
};

export type AiCarbonEstimateStatus = 'Estimated' | 'UnknownModel' | 'UnsupportedCapability';

export type AiUsagePeriod = 'Hourly' | 'Daily';

export type EstimateFeatureBreakdownModel = {
    available: boolean;
    items: Array<EstimateFeatureItemModel>;
};

export type EstimateFeatureItemModel = {
    featureType: string;
    co2eGrams: EstimateRangeModel;
    requests: number;
};

export type EstimateMethodModel = {
    source: string;
    dataVersion: string;
    electricityZone?: null | string;
    electricityZones: Array<string>;
    zoneIsOverride: boolean;
    analyticsEnabled: boolean;
};

export type EstimateModelRowModel = {
    providerId: string;
    modelId: string;
    matchedAs?: null | string;
    electricityZone?: null | string;
    status: AiCarbonEstimateStatus;
    co2eGrams?: null | EstimateRangeModel;
    requests: number;
    outputTokens: number;
    warnings: Array<string>;
};

export type EstimateNotEstimatedModel = {
    requests: number;
    outputTokens: number;
    models: number;
};

export type EstimateRangeModel = {
    min: number;
    max: number;
};

export type EstimateResponseModel = {
    from: string;
    to: string;
    granularity: AiUsagePeriod;
    total: EstimateTotalModel;
    byModel: Array<EstimateModelRowModel>;
    byFeature: EstimateFeatureBreakdownModel;
    timeSeries: Array<EstimateTimeSeriesPointModel>;
    notEstimated: EstimateNotEstimatedModel;
    method: EstimateMethodModel;
};

export type EstimateTimeSeriesPointModel = {
    timestamp: string;
    co2eGrams: EstimateRangeModel;
};

export type EstimateTotalModel = {
    co2eGrams: EstimateRangeModel;
    energyWh: EstimateRangeModel;
    requests: number;
    outputTokens: number;
};

export type ValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
    errors: {
        [key: string]: Array<string>;
    };
};

export type GetEstimateData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        granularity?: AiUsagePeriod;
    };
    url: '/umbraco/ai-carbon/management/api/v1/estimate';
};

export type GetEstimateErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetEstimateError = GetEstimateErrors[keyof GetEstimateErrors];

export type GetEstimateResponses = {
    /**
     * OK
     */
    200: EstimateResponseModel;
};

export type GetEstimateResponse = GetEstimateResponses[keyof GetEstimateResponses];
