// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://127.0.0.1:44355/' | (string & {});
};

export type AiCarbonEquivalentKindModel = 'PhoneCharges' | 'CarKm' | 'FlightKm';

export type AiCarbonEstimateStatusModel = 'Estimated' | 'UnknownModel' | 'UnsupportedCapability';

export type AiUsagePeriodModel = 'Hourly' | 'Daily';

export type EstimateEquivalentModel = {
    kind: AiCarbonEquivalentKindModel;
    amount: number;
    basisCo2eGrams: number;
    source: string;
    sourceYear: number;
};

export type EstimateFeatureBreakdownModel = {
    available: boolean;
    items: Array<EstimateFeatureItemModel>;
};

export type EstimateFeatureItemModel = {
    featureType: string;
    co2eGrams: EstimateRangeModel;
    requests: number;
};

export type EstimateMethodModel = {
    source: string;
    dataVersion: string;
    electricityZone?: string | null;
    electricityZones: Array<string>;
    zoneIsOverride: boolean;
    analyticsEnabled: boolean;
};

export type EstimateModelRowModel = {
    providerId: string;
    modelId: string;
    matchedAs?: string | null;
    electricityZone?: string | null;
    status: AiCarbonEstimateStatusModel;
    co2eGrams?: EstimateRangeModel | null;
    requests: number;
    outputTokens: number;
    warnings: Array<string>;
};

export type EstimateNotEstimatedModel = {
    requests: number;
    outputTokens: number;
    models: number;
};

export type EstimateRangeModel = {
    min: number;
    max: number;
};

export type EstimateResponseModel = {
    from: string;
    to: string;
    granularity: AiUsagePeriodModel;
    total: EstimateTotalModel;
    byModel: Array<EstimateModelRowModel>;
    byFeature: EstimateFeatureBreakdownModel;
    timeSeries: Array<EstimateTimeSeriesPointModel>;
    notEstimated: EstimateNotEstimatedModel;
    method: EstimateMethodModel;
};

export type EstimateTimeSeriesPointModel = {
    timestamp: string;
    co2eGrams: EstimateRangeModel;
};

export type EstimateTotalModel = {
    co2eGrams: EstimateRangeModel;
    energyWh: EstimateRangeModel;
    requests: number;
    outputTokens: number;
    equivalent?: EstimateEquivalentModel | null;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown;
};

export type GetEstimateData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        granularity?: AiUsagePeriodModel;
    };
    url: '/umbraco/ai-carbon/management/api/v1/estimate';
};

export type GetEstimateErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetEstimateError = GetEstimateErrors[keyof GetEstimateErrors];

export type GetEstimateResponses = {
    /**
     * OK
     */
    200: EstimateResponseModel;
};

export type GetEstimateResponse = GetEstimateResponses[keyof GetEstimateResponses];
